variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  IMAGE_TAG_ECR: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_TAG
  AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  AWS_REGION: $AWS_REGION

stages:
  - analyze
  - build
  - tag-jobs
  - tag-jobs-ecr

include:
  - project: "cdp/gitlab-templates"
    ref: master
    file: "/workflows/node/.tg-bots-jobs.yml"