version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8443:8443"
    restart: always
    networks:
      - botstats_default

networks:
  botstats_default:
    external: true
